project:
  type: website
  output-dir: docs
website:
  title: "presentation-causal-inference-matching"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: causal-inference-observational-data-matching.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



